import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/header/Navbar";
import Footer from "@/components/shared/footer/Footer";
import AOSInit from "@/animation/AOSInit";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300", "400", "500", "600", "700","800"], 
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <AOSInit/>
        <Navbar />
        <div className="min-h-[60vh]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
