import { IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/shared/LayoutWrapper";
import AOSInit from "@/animation/AOSInit";

const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700"], 
  variable: "--font-ibm-plex-serif",
});

export const metadata = {
  title: "CERVANNA CARE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSerif.variable} font-serif antialiased`}>
        <AOSInit />
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
